CREATE TABLE SOLARSYSTEMOBJECTS
(ID INTEGER NOT NULL,
ID_CLASS INTEGER,
NAME VARCHAR(20),
MASS VARCHAR(20),
DIAMETER INTEGER,
DENSITY FLOAT,
TEMPERATURE VARCHAR(26),
PRIMARY KEY (ID));
CREATE TABLE OBJECTCLASSES
(ID INTEGER NOT NULL,
NAME VARCHAR(18),
PRIMARY KEY (ID));